# Generated by Django 6.0.4 on 2026-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='stack',
            field=models.CharField(blank=True, help_text='Ex: Django · PostgreSQL · Bootstrap', max_length=150),
        ),
    ]
